### PR TITLE
Improve compatibility of code

### PR DESCRIPTION
**Pull request by mcepl**
There are two commits in this PR:

1. use ``vim.compat`` when we have it.
2. commit [implove-creation-of-uri.patch](https://gist.githubusercontent.com/erw7/506d0356881a05af017e77d1104b7d64/raw/2fc0cf45423305f6002db80ca518aeacd7dd412b/implove-creation-of-uri.patch) by @erw7 mentioned in https://github.com/neovim/neovim/pull/6856#issuecomment-443664616

### CODE REVIEW

**Comment by bfredl** [comment]
For changes of the code itself, it is better to submit them at https://github.com/neovim/neovim/pull/6856. This repo will be synced with changes to that.

**Comment by mcepl** [comment]
Well, I tried to do that (https://github.com/tjdevries/neovim/pull/2), but apparently even there nobody is at home. Never mind, I'll just develop for myself, and eventually I make new PR if anybody notices neovim/neovim#6856 again. I thought it was the point of repo to prepare changes for future inclusion into that PR, but apparently not.

**Comment by bfredl** [comment]
If @tjdevries doesn't respond, and you are interesting in taking over the work, you can open a new PR at neovim/neovim. Or discuss the changes in the PR thread, others might respond if not tjdevries.

**Comment by bfredl** [comment]
> I thought it was the point of repo to prepare changes for future inclusion into that PR, but apparently not.

The purpose right now is what the Readme says: "This is a mirror of the Nvim LSP PR by @tjdevries. It is meant to be able to test and use the client without building from this branch." We could change the dev model to a separate repo, but that would also be best to discuss at neovim/neovim#6856, where people sees it.

**Pull request closed without merging**
